# Generated by Django 2.1.7 on 2019-03-31 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapors_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('f1', models.CharField(max_length=100)),
                ('f2', models.CharField(max_length=100)),
                ('f3', models.CharField(max_length=100)),
                ('f4', models.CharField(max_length=100)),
                ('f5', models.CharField(max_length=100)),
                ('f6', models.CharField(max_length=100)),
                ('f7', models.CharField(max_length=100)),
                ('f8', models.CharField(max_length=100)),
                ('f9', models.CharField(max_length=100)),
                ('f10', models.CharField(max_length=100)),
                ('f11', models.CharField(max_length=100)),
                ('f12', models.CharField(max_length=100)),
                ('f13', models.CharField(max_length=100)),
                ('f14', models.CharField(max_length=100)),
                ('f15', models.CharField(max_length=100)),
                ('f16', models.CharField(max_length=100)),
                ('f17', models.CharField(max_length=100)),
                ('f18', models.CharField(max_length=100)),
                ('f19', models.CharField(max_length=100)),
                ('f20', models.CharField(max_length=100)),
                ('f21', models.CharField(max_length=100)),
                ('f22', models.CharField(max_length=100)),
                ('f23', models.CharField(max_length=100)),
                ('f24', models.CharField(max_length=100)),
                ('f25', models.CharField(max_length=100)),
                ('f26', models.CharField(max_length=100)),
                ('f27', models.CharField(max_length=100)),
            ],
        ),
    ]
