# Generated by Django 2.1.7 on 2019-04-01 21:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapors_app', '0003_auto_20190401_1746'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogcomments',
            name='Name',
            field=models.CharField(default='demo', max_length=100),
        ),
        migrations.AddField(
            model_name='blogcomments',
            name='Social_fear',
            field=models.CharField(default='Demo', max_length=100),
        ),
    ]
