# Generated by Django 2.1.7 on 2019-04-01 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapors_app', '0004_auto_20190402_0232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogcomments',
            name='Social_fear',
            field=models.CharField(max_length=100),
        ),
    ]
