# Generated by Django 2.1.7 on 2019-04-01 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Vapors_app', '0005_auto_20190402_0234'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('Age', models.IntegerField(default=20)),
                ('Gender', models.CharField(max_length=100)),
                ('Sexuality', models.CharField(max_length=100)),
                ('Body_weight', models.CharField(max_length=100)),
                ('Virgin', models.CharField(max_length=100)),
                ('Prostitution_legal', models.CharField(max_length=100)),
                ('Pay_for_sex', models.CharField(max_length=100)),
                ('Friends', models.CharField(max_length=100)),
                ('Social_fear', models.CharField(max_length=100)),
                ('PHQ1A', models.CharField(max_length=100)),
                ('PHQ1B', models.CharField(max_length=100)),
                ('PHQ1C', models.CharField(max_length=100)),
                ('PHQ1D', models.CharField(max_length=100)),
                ('PHQ9', models.CharField(max_length=100)),
                ('PHQ6A', models.CharField(max_length=100)),
                ('PHQ6B', models.CharField(max_length=100)),
                ('PHQ6C', models.CharField(max_length=100)),
                ('PHQ6D', models.CharField(max_length=100)),
                ('PHQ2A', models.CharField(max_length=100)),
                ('PHQ2B', models.CharField(max_length=100)),
                ('PHQ2C', models.CharField(max_length=100)),
                ('PHQ3', models.CharField(max_length=100)),
                ('PHQ4A', models.CharField(max_length=100)),
                ('PHQ4B', models.CharField(max_length=100)),
                ('PHQ4C', models.CharField(max_length=100)),
                ('PHQ8', models.CharField(max_length=100)),
                ('PHQ5', models.CharField(max_length=100)),
                ('PHQ7A', models.CharField(max_length=100)),
                ('PHQ7B', models.CharField(max_length=100)),
                ('PHQ7C', models.CharField(max_length=100)),
                ('PHQ7D', models.CharField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='BlogComments',
        ),
    ]
